name = "sfw-hub"
compatibility_date = "2024-05-01"

[vars]
ADMIN_KEY = "DEFINIR_NO_DASHBOARD"
PUBLIC_R2 = "https://pub-0a153dc652084377852df5ed979f83db.r2.dev"

[[d1_databases]]
binding = "DB"
database_name = "sfwdb"
database_id = "YOUR_DATABASE_ID_HERE"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "sfw-bucket"

[site]
bucket = "./dist"
